server:
  port: 8002

spring:
  application:
    name: AVAILABILITY-API
  datasource:
    url: jdbc:postgresql://localhost:5432/availabilitydb
    username: postgres
    password: Qwerty@123
  redis:
    host: localhost
    port: 6379
    connect-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

